appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ogz43y7Ray+eNdCb9ZhZ/fIsChR62B2cWUYHqEGEVRJh+yXqg/yN/In1FQpFMWkGmdBzIxIn0/3Fp4IexC8YibeAnkZTZUhN7CgOK2+Ceso7P6Q7HLOzXZ60K1Bue2JbqE3WQGMlXL42/GVg+NeGoMLsfqECVXWdIt+xPMtYlnjneBcX/CvyaWajQJf44Nga0HEeGJVXB1ReVNG/+ZJyu5CTcuzUtpB3/Jvjh7YKEJ28KZZPy220rwbCwUo80DlEOu9UKuVEyPw46Dj5wkNq5cllpu8GTcvFWd9geIdHysa6E0vnO8e5gX92TVyxCHCnRGryL7GNYNqvo2ZmQZEficyx7OU8vMyf4egRvpuZOJ4tW4gtDCwfzHTnY7NvYw3B+tWSH8UIb9/Jv2zOJBOXdWQcvWzytRWy91R/xNcn2c65nM4ZV9lpZWcIM6FGUpqNKfT9isIPnFglXW8gqOivuRkgtQh9u388TKLqAD0p5TfAR28hSADyXO4jlPV31x0wHrhWB9BamaLUvLyBgF7w4SzTbXF9bYKYgy4N5FNuvuGEh/Dum3xT4BTUQ6gQ0udHIh+NgPpFQVpxcojDCRLMheJ/UfDBb48xB8CuYiH3JKc4JFvlcG2sAxmqShegL2ondrz38Xqb7aFTSZjsK81xImcyMsZ9SITdwilfxdNfXYw=}
